### ISSUE TITLE
onRainbowError() : XMPPERROR

### ISSUE THREAD

**Issue by spady7** [Rainbow-CPaaS/node-red-contrib-ale-rainbow#5] opened 2018-01-19 21:01 UTC
Hi,
working on our BOT project using Rainbow Node-red Contrib i noticed that when message to BOT comes from mobile client, rainbow user used by rainbow-node-red-contrib goes off-line and then it comes back on-line and never reply to initial sent message.

This happens ONLY from Mobile Rainbow Client; if i make same test from Desktop client or web client NEVER happens.

I collect some logs and I can see some errors like following:

0|node-red | 19 Jan 16:06:30 - [info] [Notified_IM:541b43dd.a3d7fc] Rainbow : onMessageReceived
0|node-red | 19 Jan 16:06:30 - [info] [Notified_IM:541b43dd.a3d7fc] Rainbow : Message :{"fromJid":"xxxxxxxxxxxxxxxxxxxxxxxxx@openrainbow.com","resource":"mobile_android_3xxxxxxxxxxxxxxxxxxxxxxxxx","toJid":"xxxxxxxxxxxxxxxxxxxxxxxxx@openrainbow.com/node_sXEDWiay","type":"chat","content":"#pb carini","alternativeContent":[],"id":"38uZg-2253","cc":false,"cctype":"","isEvent":false,"oob":null}
0|node-red | 2018-1-19 16:06:32 [1516374392291] - debug: XMPP - (handleXMPPConnection) raw in - << <stream:error xmlns:stream='http://etherx.jabber.org/streams'><invalid-from xmlns='urn:ietf:params:xml:ns:xmpp-streams'></invalid-from></stream:error>
0|node-red | 2018-1-19 16:06:32 [1516374392294] - info: XMPP - (handleXMPPConnection) event - status | closing
0|node-red | 2018-1-19 16:06:32 [1516374392296] - debug: XMPP - (handleXMPPConnection) raw out - >> <close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>
0|node-red | 2018-1-19 16:06:32 [1516374392297] - debug: XMPP - (handleXMPPConnection) event - error | invalid-from
0|node-red | 19 Jan 16:06:32 - [info] [Login:Service#2] ////////////////
0|node-red | 19 Jan 16:06:32 - [info] [Login:Service#2] onRainbowError() : XMPPERROR
0|node-red | 19 Jan 16:06:32 - [info] [Login:Service#2] ////////////////
0|node-red | 2018-1-19 16:06:32 [1516374392301] - debug: XMPP - (handleXMPPConnection) raw in - << <close xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>
0|node-red | 2018-1-19 16:06:32 [1516374392302] - info: XMPP - (handleXMPPConnection) event - status | close
0|node-red | 2018-1-19 16:06:32 [1516374392303] - debug: XMPP - (handleXMPPConnection) event - close |<close xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>
0|node-red | 2018-1-19 16:06:32 [1516374392305] - info: XMPP - (handleXMPPConnection) event - status | disconnecting
0|node-red | 2018-1-19 16:06:32 [1516374392308] - info: XMPP - (handleXMPPConnection) event - status | disconnect
0|node-red | 2018-1-19 16:06:32 [1516374392310] - debug: XMPP - (handleXMPPConnection) event - disconnect |
0|node-red | 2018-1-19 16:06:32 [1516374392311] - info: STATEMGR - (transitTo) set state disconnected
0|node-red | 2018-1-19 16:06:32 [1516374392312] - info: EVENTS - (publish) event rainbow_ondisconnected
0|node-red | 2018-1-19 16:06:32 [1516374392314] - debug: XMPP - (handleXMPPConnection) plugin event - reconnecting
0|node-red | 2018-1-19 16:06:32 [1516374392315] - debug: XMPP -  (handleXMPPConnection) update reconnect delay - 5151 ms
0|node-red | 2018-1-19 16:06:32 [1516374392316] - info: STATEMGR - (transitTo) set state reconnecting
0|node-red | 2018-1-19 16:06:32 [1516374392316] - info: EVENTS - (publish) event rainbow_onreconnecting

**Comment by ArfyFR** [comment] 2018-01-19 22:02
Weird if it comes only from Mobile.
I'll have to also check the used Rainbow Nodejs SDK library + perhaps server (I hope not).

@spady7, could you tell me if it is an Android mobile client ?  Or from iPhone ? (or both)

Thanks for the information !

Adding/pinging also @oanguenot

**Comment by ArfyFR** [comment] 2018-01-19 22:57
@spady7 : sorry, I just saw in logs it is from an Android.
Other question: 
Problem occurred with a message to IM or to Bubble or to both ?

**Comment by spady7** [comment] 2018-01-19 23:54
Hi, yes it was from Android. I had some BOT installation on different server and different company but issue is always present.
I had right now some test from iPhone and seams it is not affected by this issue. Seams work fine.
I am using it sending messages to IM; but at beginning i was using also sending messages to Bubble and issue was present as well.
So it seams only Android mobiles affected. (I tested it from different Android smartphone; different smartphone models as well)
If you need more details, just ask me.
Regards

**Comment by ArfyFR** [comment] 2018-01-20 08:18
In order to work with Android team Monday, could you confirm my understanding of your BOT project ?

User A: Rainbow Android, sends an IM to user B
User B:
- Node-red is notified with "Notified_IM" node, 
- but faces the "`onRainbowError() : XMPPERROR`" => **BUG** here, I don't know yet if it is from Android or server's side
- and refresh (this is normal ... as it gets next a `status | closing` **from the XMPP server**)
- after reconnexion, the IM from User A (Android) is lost/no more notified

Another question: Could you also send/confirm me your Rainbow Android version please ?
( Last in https://play.google.com/store/apps/details?id=com.ale.rainbow seems to be 1.35.1 )

**Comment by spady7** [comment] 2018-01-20 09:02
Hi  you perfect understood!! Scenario is as described by you!!
I also can confirm you that I am using last version 1.35.1.
I had test from Galaxy s7 edge... s4 mini... and other kind of Android mobiles but issue is always the same.
Feel free to ask other tests.
Regards

**Comment by ArfyFR** [comment] 2018-01-20 09:25
Thanks.
I don't think it can be linked to one Android or another.

Last question (_perhaps_ ;) ), it make node-red Rainbow down with all types of messages ?
I mean, I saw the
`"content":"#pb carini"`
in the the logs you provided.

1. The problem occurs whatever you write/send ?  
2. Or with a specific format (_like here a # at the beginning_) ?
3. If it is a specific format: did you test this format also from iPhone ?

**Comment by spady7** [comment] 2018-01-20 09:53
Hi... issue is present whatever I write. #... is a character used on my BOT but is not related to it. I tried writing normal words and seams again only from Android mobiles. From iPhone seams ok. Anyway on Monday I 'll have more tests from iPhone as well. 
Anyway I can confirm that from Android there is a bug. 

P.S. the very weird thing is that some times works also from Android..  it works for a while... (some Im sent... ) then bug appears again. 
Regards

**Comment by ArfyFR** [comment] 2018-01-20 13:24
Thanks for your PS.  Good to know it is not 100% reproductible.

We will have to compare the xmpp messages sent by Android / how it is managed-transferred by server and verify if the "close" is from the server or from the node-red.

Last request: could you send me an email (cf my profile) with recent logs not obfuscated please ?
It's for the server team to find error logs.

**Comment by spady7** [comment] 2018-01-20 20:48
Ok, logs sent.
Regards

**Comment by ArfyFR** [comment] 2018-01-21 07:53
Thanks for the full logs.  I sent them to Android team and Server support team.

It seems (in this logs) that the problem occurred during the "resend phase" from Nodejs SDK to Rainbow with a
`<stream:error xmlns:stream='http://etherx.jabber.org/streams'><invalid-from xmlns='urn:ietf:params:xml:ns:xmpp-streams'></invalid-from></stream:error>`
as if the `from` looks/is OK as used previously.

In the logs you put in in issue at the top, you also cut/obfuscate what was in the `stream:error` ?

I was wondering if the problem (XMPP down) only occurs sometimes on **_resend_** or (like I understand first) also at **_receive_**.

**Comment by ArfyFR** [comment] 2018-01-24 10:08
I'll close this issue as it is no more reproductible in my tests.
I think it was a problem with the Rainbow Node.js SDK which wasn't up to date.

**Closed as completed by ArfyFR** 2018-01-24 10:08 UTC
Labels: bug
